name: SonarCloud
on:
  push:
    branches:
      - sonarcloud
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Analyze with SonarCloud
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=M-N-21_GestionImpotSpringBoot
        env:
          GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
